name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Install dependencies
      run: |
        npm install

    - name: Build the project
      run: |
        npm run build

    - name: Run tests
      run: |
        nohup npm run dev &
        sleep 30
